### ISSUE TITLE
我用了这个插件感觉速度没有什么提升，我看了您的速度提升大概有一秒，感觉这个插件不是很有效啊？

### ISSUE THREAD

**Issue by IceyIsAlreadyTaken** [beichensky/webpack-demo#1]

**Comment by beichensky** [comment]
您说的是` happypack` 插件吗？这个我在博客里也有提到：
- 如果是一些小型的项目，使用 `happypack`，速度提升不明显，甚至有可能导致构建速度变慢；
- 只有在一些比较复杂的大中型项目中，使用 `happypack` 才可能看到比较明显的速度提升；
- 使用 `happypack` 时需要根据具体情况进行选择，如果反而延长了项目的构建速度，就没有必要使用 `happypack` 了。

**Comment by IceyIsAlreadyTaken** [comment]
是dllplugin这个插件，感觉速度没有提升

**Comment by beichensky** [comment]
您在使用的时候，将哪些库作为了 dll 动态链接呢？
我当前的 demo 里面引用的模块比较少，只使用了 `lodash` 作为演示，所以构建速度提升不明显。
如果引用的模块较多，比如 `react`、`react-dom`、`react-router-dom` 以及 `mobx` 等，都作为 `dll` 动态链接库进行构建时，用来和之前进行比较，是可以看到很明显的速度提升的。

**Comment by IceyIsAlreadyTaken** [comment]
设置的库还蛮多的，有十五个左右，但是速度感觉没有什么变化

**Comment by beichensky** [comment]
方便把您使用 `DllPlugin` 配置的库，以及使用 `DllPlugin` 和 `DllReferencePlugin` 插件相关的代码贴出来看一下吗？

**Comment by IceyIsAlreadyTaken** [comment]
嗯嗯，好的，这是我的部分代码
vender.js 文件：
require("classnames");
require("i18next");
require("i18next-browser-languagedetector");
require("i18next-xhr-backend");
require("js-base64");
require("mobx");
require("mobx-react");
require("moment");
require("object-assign");
require("pinyin");
require("promise");
require("qs");
require("query-string");
require("react");
require("react-dom");
require("react-i18next");
require("react-image");

webpack.dll.js文件
var path = require("path");
var webpack = require("webpack");

module.exports = {
  entry: {
    vendor: [path.join(__dirname, "vendors.js")]
  },
  output: {
    path: path.join(__dirname, "dll"),
    filename: "dll.[name].js",
    library: "[name]"
  },
  plugins: [
    new webpack.DllPlugin({
      path: path.join(__dirname, "[name]-manifest.json"),
      name: "[name]",
      context: __dirname
    }),
    new webpack.optimize.OccurrenceOrderPlugin(),
    new webpack.optimize.UglifyJsPlugin()
  ],
  resolve: {
    modules: ["node_modules"]
  }
};


webpack.config.dev.js文件
new webpack.DllReferencePlugin({
      // context: __dirname,
      manifest: require("./vendor-manifest.json")
    })

我是在模板文件中手动引入的生成的dll.vender.js文件

**Comment by beichensky** [comment]
目前看下来配置应该是正常的。您现在项目启动时耗时多久？热更新时一般耗时为多久呢？

**Comment by beichensky** [comment]
目前看下来配置应该是正常的。您现在项目启动时耗时多久？热更新时一般耗时为多久呢？比较没有使用 `dll` 之前，构建速度分别有提升吗？

**Comment by beichensky** [comment]
目前看下来配置应该是正常的。您现在项目启动时耗时多久？热更新时一般耗时为多久呢？比较没有使用 dll 之前，构建速度分别有提升吗？另外想冒昧的问一下，您这个项目打包之后有多大?

**Comment by IceyIsAlreadyTaken** [comment]
可否加个好友详细请教下呢，我已经申请加您qq了

**Comment by beichensky** [comment]
没问题的，大家可以一起探讨一下。不过我这边还没有收到您的申请信息。
